name: Build and test inline xbrl examples
on:
  push:
  workflow_dispatch:

jobs:
  ping_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          type="trigger-workflow"
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sbr-nl/cicd/actions/workflows/report-integration.yaml/dispatches \
            -d '{"ref":"${{ github.ref }}", "inputs": {"branch": "${{ github.ref_name }}", "repository": "${{ github.repository }}", "message": "Ping! " }}'
